backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img"


collections:
  - name: 'paginas'
    label: 'Páginas Fuso'
    editor:
      preview: false
    files:
      - label: 'Geral'
        name: geral
        file: '_data/index.yml'
        fields: 
          - {label: 'Data Fuso', name: fuso_data, widget: string}
          - {label: 'Data Fuso Insular', name: insular_data, widget: string}
          - { label: 'Côr', name: colour, widget: color }
          - label: 'Fase Fuso'
            name: fase
            widget: select
            options: 
              - { label: "Pré-Programa", value: 0 }
              - { label: "Programa Fuso", value: 1 }
              - { label: "Pós-Programa", value: 2 }
          - label: 'Fase Insular'
            name: fase-insular
            widget: select
            options: 
              - { label: "Pré-Programa", value: 0 }
              - { label: "Programa Fuso", value: 1 }
              - { label: "Pós-Programa", value: 2 }
          - {label: 'Imagem Open Call PT', name: imagem_opencall_pt, widget: image, required: false}
          - {label: 'Imagem Open Call PT Mobile', name: imagem_opencall_pt_mobile, widget: image, required: false}
          - {label: 'Imagem Open Call ENG', name: imagem_opencall_eng, widget: image, required: false}          
          - {label: 'Imagem Open Call ENG Mobile', name: imagem_opencall_eng_mobile, widget: image, required: false}
          - {label: 'Imagem Datas Fuso PT', name: imagem_datas_pt, widget: image, required: false}
          - {label: 'Imagem Datas Fuso PT Mobile', name: imagem_datas_pt_mobile, widget: image, required: false}
          - {label: 'Imagem Datas Fuso ENG', name: imagem_datas_eng, widget: image, required: false}
          - {label: 'Imagem Datas Fuso ENG Mobile', name: imagem_datas_eng_mobile, widget: image, required: false}
          - {label: 'Imagem Lab PT', name: imagem_lab_pt, widget: image, required: false}
          - {label: 'Imagem Lab PT Mobile', name: imagem_lab_pt_mobile, widget: image, required: false}
          - {label: 'Imagem Lab ENG', name: imagem_lab_eng, widget: image, required: false}
          - {label: 'Imagem Lab ENG Mobile', name: imagem_lab_eng_mobile, widget: image, required: false}
          - {label: 'Imagem Datas Insular PT', name: imagem_datas_ins_pt, widget: image, required: false}
          - {label: 'Imagem Datas Insular PT Mobile', name: imagem_datas_ins_pt_mobile, widget: image, required: false}
          - {label: 'Imagem Datas Insular ENG', name: imagem_datas_ins_eng, widget: image, required: false}
          - {label: 'Imagem Datas Insular ENG Mobile', name: imagem_datas_ins_eng_mobile, widget: image, required: false}
      - label: 'Sobre'
        name: 'sobre'
        file: '_data/sobre-fuso.yml'
        fields: 
          - {label: 'Informação', name: informacao, widget: markdown, modes: [rich_text]}
          - {label: 'Informação ENG', name: informacao_eng, widget: markdown, modes: [rich_text]}
          - label: 'Ficha Técnica'
            name: ficha_tecnica
            widget: list
            fields:
              - {name: title_pt, widget: string, label: 'Titulo PT'}
              - {name: title_eng, widget: string, label: 'Titulo ENG'}
              - {name: name, widget: string, label: 'Nome'}
      - label: 'Open Call'
        name: 'open_call'
        file: '_data/open-call.yml'
        fields: 
          - {label: 'Regulamento', name: regulamento, widget: markdown, modes: [rich_text]}
          - {label: 'Regulamento ENG', name: regulamento_eng, widget: markdown, modes: [rich_text]}
          - {name: image, widget: image, label: 'Imagem PT'}
          - {name: image_eng, widget: image, label: 'Imagem ENG'}
      - label: 'Curadores'
        name: curadores
        file: '_data/fuso_curators.yml'
        fields: 
          - {label: 'Intro', name: intro_pt, widget: markdown, modes: [rich_text]}
          - {label: 'Intro ENG', name: intro_eng, widget: markdown, modes: [rich_text]}
          - label: 'Curadores'
            name: curadores
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
              - {name: retrato, widget: image, label: 'Retrato'}
      - label: 'Artists'
        name: artistas
        file: '_data/fuso_artists.yml'
        fields: 
          - label: 'Artists'
            name: artistas
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
      - label: 'Parceiros Fuso'
        name: parceiros-fuso
        file: '_data/parceiros-footer.yml'
        fields: 
          - label: 'Produção'
            name: producao
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Financiamento'
            name: financiamento
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Parceria Institucional'
            name: institucional
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Apoio'
            name: partner
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Apoio à divulgação'
            name: media
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Acolhimento'
            name: hosts
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Parceria'
            name: parceria
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
  - name: 'paginas_insular'
    label: 'Páginas Insular'
    editor:
      preview: false
    files:
      - label: 'Sobre'
        name: 'sobre'
        file: '_data/sobre-insular.yml'
        fields: 
          - {label: 'Informação', name: informacao, widget: markdown, modes: [rich_text]}
          - {label: 'Informação ENG', name: informacao_eng, widget: markdown, modes: [rich_text]}
          - label: 'Ficha Técnica'
            name: ficha_tecnica
            widget: list
            fields:
              - {name: title_pt, widget: string, label: 'Titulo PT'}
              - {name: title_eng, widget: string, label: 'Titulo ENG'}
              - {name: name, widget: string, label: 'Nome'}
      - label: 'Laboratório'
        name: 'laboratorio'
        file: '_data/laboratorio.yml'
        fields: 
          - {label: 'Regulamento', name: regulamento, widget: markdown, modes: [rich_text]}
          - {label: 'Regulamento ENG', name: regulamento_eng, widget: markdown, modes: [rich_text]}
          - {name: image, widget: image, label: 'Imagem PT'}
          - {name: image_eng, widget: image, label: 'Imagem ENG'}
      - label: 'Curadores'
        name: curadores
        file: '_data/insular_curators.yml'
        fields: 
          - {label: 'Intro', name: intro_pt, widget: markdown, modes: [rich_text]}
          - {label: 'Intro ENG', name: intro_eng, widget: markdown, modes: [rich_text]}
          - label: 'Curadores'
            name: curadores
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
              - {name: retrato, widget: image, label: 'Retrato'}
      - label: 'Artists'
        name: artistas
        file: '_data/insular_artists.yml'
        fields: 
          - label: 'Artists'
            name: artistas
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
      - label: 'Parceiros Insular'
        name: parceiros-insular
        file: '_data/parceiros-insular.yml'
        hint: 'tamanho recomendado: 245×130'
        fields: 
          - label: 'Produção'
            name: producao
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Financiamento'
            name: financiamento
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Co-Produção'
            name: co-prod
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Apoio'
            name: apoio
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
          - label: 'Parceria'
            name: parceria
            hint: 'tamanho recomendado: 245×130, fundo transparente (png)'
            widget: list
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image}
  - name: 'fuso_programs'
    label: 'Programas Fuso'
    folder: '_fuso_programs'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: curadoria, widget: string, label: 'Curadoria'}
      - {name: data, widget: string, label: 'Dia'}
      - {name: month_pt, widget: string, label: 'Mês PT'}
      - {name: month_eng, widget: string, label: 'Month ENG'}
      - label: "Data (para ordem)"
        name: "start"
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
        format: "LLL"
        picker_utc: false
      - {name: local,  widget: markdown, modes: [rich_text], required: false, label: 'Local'}
      - {name: horas, widget: string, required: false, label: 'Horas'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {label: 'Texto Curatorial', name: texto_curatorial, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Texto Curatorial ENG', name: texto_curatorial_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: link_vimeo, widget: string, label: 'Link Vimeo'}
      - {name: layout, widget: hidden, default: 'programa', label: 'Layout'}
  - name: 'fuso_eventos'
    label: 'Eventos Fuso'
    folder: '_fuso_eventos'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: artista, widget: string, label: 'Artista'}
      - {name: programa, label: 'Programa', widget: relation, collection: 'fuso_programs', search_fields: ['title'], value_field: '_fuso_programs/{{filename}}.{{extension}}', display_fields: ['title']}
      - {name: ano, widget: string, required: false, label: 'Ano'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {name: hora, widget: string, required: false, label: 'Hora'}
      - {label: 'Sinopse', name: sinopse, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Synopsis', name: sinopse_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: credito_imagem, widget: string, label: 'Crédito Imagem'}
      - {name: layout, widget: hidden, default: 'evento', label: 'Layout'}
  - name: 'insular_programs'
    label: 'Programas Insular'
    folder: '_insular_programas'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: curadoria, widget: string, label: 'Curadoria'}
      - {name: data, widget: string, label: 'Dia'}
      - {name: month_pt, widget: string, label: 'Mês PT'}
      - {name: month_eng, widget: string, label: 'Month ENG'}
      - {name: local,  widget: markdown, modes: [rich_text], required: false, label: 'Local'}
      - {name: horas, widget: string, required: false, label: 'Horas'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {label: 'Texto Curatorial', name: texto_curatorial, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Texto Curatorial ENG', name: texto_curatorial_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: link_vimeo, widget: string, label: 'Link Vimeo'}
      - {name: layout, widget: hidden, default: 'programa-insular', label: 'Layout'}
  - name: 'insular_eventos'
    label: 'Eventos Insular'
    folder: '_insular_eventos'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: artista, widget: string, label: 'Artista'}
      - {name: programa, label: 'Programa', widget: relation, collection: 'insular_programs', search_fields: ['title'], value_field: '_insular_programas/{{filename}}.{{extension}}', display_fields: ['title']}
      - {name: ano, widget: string, required: false, label: 'Ano'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {name: hora, widget: string, required: false, label: 'Hora'}
      - {label: 'Sinopse', name: sinopse, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Synopsis', name: sinopse_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: credito_imagem, widget: string, label: 'Crédito Imagem'}
      - {name: layout, widget: hidden, default: 'evento-insular', label: 'Layout'}
