backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img"


collections:
  - name: 'paginas'
    label: 'Páginas Fuso'
    editor:
      preview: false
    files:
      - label: 'Geral'
        name: geral
        file: '_data/index.yml'
        fields: 
          - {label: 'Data Fuso', name: fuso_data, widget: string}
          - {label: 'Mês Fuso', name: fuso_mes, widget: string}
          - {label: 'Data Fuso Insular', name: insular_data, widget: string}
          - {label: 'Mês Fuso Insular', name: insular_mes, widget: string}
          - { label: 'Côr', name: colour, widget: color }
      - label: 'Sobre'
        name: 'sobre'
        file: '_data/sobre-fuso.yml'
        fields: 
          - {label: 'Informação', name: informacao, widget: markdown, modes: [rich_text]}
          - {label: 'Informação ENG', name: informacao_eng, widget: markdown, modes: [rich_text]}
      - label: 'Open Call'
        name: 'open_call'
        file: '_data/open-call.yml'
        fields: 
          - {label: 'Regulamento', name: regulamento, widget: markdown, modes: [rich_text]}
          - {label: 'Regulamento ENG', name: regulamento_eng, widget: markdown, modes: [rich_text]}
      - label: 'Curadores'
        name: curadores
        file: '_data/fuso_curators.yml'
        fields: 
          - {label: 'Intro', name: intro_pt, widget: markdown, modes: [rich_text]}
          - {label: 'Intro ENG', name: intro_eng, widget: markdown, modes: [rich_text]}
          - label: 'Curadores'
            name: curadores
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
              - {name: retrato, widget: image, label: 'Retrato'}
      - label: 'Artists'
        name: artistas
        file: '_data/fuso_artists.yml'
        fields: 
          - label: 'Artists'
            name: artistas
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
              
  - name: 'paginas_insular'
    label: 'Páginas Insular'
    editor:
      preview: false
    files:
      - label: 'Sobre'
        name: 'sobre'
        file: '_data/sobre-insular.yml'
        fields: 
          - {label: 'Informação', name: informacao, widget: markdown, modes: [rich_text]}
          - {label: 'Informação ENG', name: informacao_eng, widget: markdown, modes: [rich_text]}
      - label: 'Laboratório'
        name: 'laboratorio'
        file: '_data/laboratorio.yml'
        fields: 
          - {label: 'Regulamento', name: regulamento, widget: markdown, modes: [rich_text]}
          - {label: 'Regulamento ENG', name: regulamento_eng, widget: markdown, modes: [rich_text]}
      - label: 'Curadores'
        name: curadores
        file: '_data/insular_curators.yml'
        fields: 
          - {label: 'Intro', name: intro_pt, widget: markdown, modes: [rich_text]}
          - {label: 'Intro ENG', name: intro_eng, widget: markdown, modes: [rich_text]}
          - label: 'Curadores'
            name: curadores
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
              - {name: retrato, widget: image, label: 'Retrato'}
      - label: 'Artists'
        name: artistas
        file: '_data/insular_artists.yml'
        fields: 
          - label: 'Artists'
            name: artistas
            widget: list
            summary: '{{fields.title}}'
            fields:
              - {name: title, widget: string, label: 'Nome'}
              - {label: 'Bio PT', name: bio_pt, widget: markdown, modes: [rich_text]}
              - {label: 'Bio ENG', name: bio_eng, widget: markdown, modes: [rich_text]}
  - name: 'fuso_programs'
    label: 'Programas Fuso'
    folder: '_fuso_programs'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: curadoria, widget: string, label: 'Curadoria'}
      - {name: data, widget: select, required: false, label: 'Data', options: ['22', '23', '24', '25', '26', '27']}
      - {name: local,  widget: markdown, modes: [rich_text], required: false, label: 'Local'}
      - {name: horas, widget: string, required: false, label: 'Horas'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {label: 'Texto Curatorial', name: texto_curatorial, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Texto Curatorial ENG', name: texto_curatorial_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: link_vimeo, widget: string, label: 'Link Vimeo'}
      - {name: layout, widget: hidden, default: 'programa', label: 'Layout'}
  - name: 'fuso_eventos'
    label: 'Eventos Fuso'
    folder: '_fuso_eventos'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: artista, widget: string, label: 'Artista'}
      - {name: programa, label: 'Programa', widget: relation, collection: 'fuso_programs', search_fields: ['title'], value_field: '_fuso_programs/{{filename}}.{{extension}}', display_fields: ['title']}
      - {name: ano, widget: string, required: false, label: 'Ano'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {name: hora, widget: string, required: false, label: 'Hora'}
      - {label: 'Sinopse', name: sinopse, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Synopsis', name: sinopse_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: credito_imagem, widget: string, label: 'Crédito Imagem'}
      - {name: layout, widget: hidden, default: 'evento', label: 'Layout'}
  - name: 'insular_programs'
    label: 'Programas Insular'
    folder: '_insular_programas'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: curadoria, widget: string, label: 'Curadoria'}
      - {name: data, widget: select, required: false, label: 'Data', options: ['26', '27', '28', '29']}
      - {name: local,  widget: markdown, modes: [rich_text], required: false, label: 'Local'}
      - {name: horas, widget: string, required: false, label: 'Horas'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {label: 'Texto Curatorial', name: texto_curatorial, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Texto Curatorial ENG', name: texto_curatorial_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: link_vimeo, widget: string, label: 'Link Vimeo'}
      - {name: layout, widget: hidden, default: 'programa-insular', label: 'Layout'}
  - name: 'insular_eventos'
    label: 'Eventos Insular'
    folder: '_insular_eventos'
    create: true
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {name: title, widget: string, label: 'Titulo'}
      - {name: title_eng, widget: string, label: 'Title ENG'}
      - {name: artista, widget: string, label: 'Artista'}
      - {name: programa, label: 'Programa', widget: relation, collection: 'insular_programs', search_fields: ['title'], value_field: '_insular_programas/{{filename}}.{{extension}}', display_fields: ['title']}
      - {name: ano, widget: string, required: false, label: 'Ano'}
      - {name: duracao, widget: string, required: false, label: 'Duração'}
      - {name: hora, widget: string, required: false, label: 'Hora'}
      - {label: 'Sinopse', name: sinopse, required: false, widget: markdown, modes: [rich_text]}
      - {label: 'Synopsis', name: sinopse_eng, required: false, widget: markdown, modes: [rich_text]}
      - {name: imagem, widget: image, label: 'Imagem'}
      - {name: credito_imagem, widget: string, label: 'Crédito Imagem'}
      - {name: layout, widget: hidden, default: 'evento-insular', label: 'Layout'}
